---
title: "Morality and Moral Judgements"
subtitle: "On-going (and potential) Projects for VIP-R Collaboration"
author: "Dr Cillian McHugh"
date: "Autumn 2020"
csl: "../../../Research_general/resources/bib/apa.csl"
bibliography: "../../../Research_general/resources/bib/My Library.bib"
output:
  bookdown::html_document2:
    fig_caption: yes
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 4
    number_sections: false
editor_options: 
  chunk_output_type: console
---
<style type="text/css">
  .table-container {
  width: 100%;
  overflow-x: scroll;
}
</style>


# On-going Morality Research:
- Moral Judgement as Categorisation
  - Meaning Maintenance and Morality
- Moral Dumbfounding
- Miscellaneous: Identity, and Networks


## Moral Judgement as Categorisation
- See [\color{blue}this paper currently under review\color{black}](https://psyarxiv.com/72dzp/)

### Testable Predictions/Possible Studies
- Typicality in moral categorisations?
- Non-moral dumbfounding
- Equivalent contextual influences
  - e.g., order effects (ethics approved)
- Additional predictions in Table 2 in paper

### Meaning Maintenance and Morality
- *Difficult* Moral judgements as a threat to meaning
- Test *fluid compensation* in non-moral paradigm (ethics approved)
- Test *fluid compensation* in moral paradigm (ethics approved)
  - Some data collected 

## Moral Dumbfounding
- Cognitive Load Studies (ethics approved)
- Distancing Studies (ethics approved)
- Non-Weird Studies (ethics approved)
- **Individual Differences** e.g., Personality (ethics approved)

## Miscellaneous: Identity, and Networks
- Morality, Identity, and Networks:
  - Reanalyse Moral Foundations data (no ethics needed)
- Proposed Pre-registered Replication of  Novel Dilemma study [[@railton_moral_2017]](https://drive.google.com/drive/folders/1-D_LgP687zYjRG5893pzAUYDykFt-F3I?usp=sharing)
- Disgust Sensitivity and Emotional Differentiation



# References
